#mode
mode:
  development
#mode=production

###############datasource config##################
#mysql,mongodb,redis等数据源配置方式
development:
    datasources:
        mysql:
           host: 120.26.205.103
           port: 3308
           database: atisws
           username: root
           password: hz52msm!..
           characterEncoding: UTF-8
           useUnicode: true
           disable: false
        mongodb:
           host: 127.0.0.1
           port: 27017
           database: wow
           disable: true
        redis:
            host: 127.0.0.1
            port: 6379
            disable: false

test:
    datasources:
            mysql:
               host: 127.0.0.1
               port: 3306
               database: wow
               username: root
               password: root
               disable: true
            mongodb:
               host: 127.0.0.1
               port: 27017
               database: wow
               disable: true
            redis:
                host: 127.0.0.1
                port: 6379
                disable: true
production:
    datasources:
            mysql:
               host: rdsjsf064n8rb16s75c5.mysql.rds.aliyuncs.com
               port: 3306
               database: umusic
               username: umusic
               password: Q!w@e#r$
               characterEncoding: UTF-8
               useUnicode: true
               disable: false
            mongodb:
               host: 127.0.0.1
               port: 27017
               database: wow
               disable: true
            redis:
                host: 127.0.0.1
                port: 6379
                disable: false

###############application config##################
#'model' for relational database  like MySQL
#'document' for NoSQL database model configuration,  MongoDB

application:
    controller: com.atis.controller.http
    model:      com.atis.model
    document:   com.example.document
    service:    com.atis.service
    util:       com.atis.util
    test:       test.com.example
    template:
        engine:
           enable: false
    api:
        qps:
           enable: true
###############http config##################
http:
    port: 9002
    disable: false

#thrift:
#    disable: true
#    services:
#        net_csdn_controller_thrift_impl_CBayesianQueryServiceImpl:
#           port: 9001
#           min_threads: 100
#           max_threads: 1000
#
#    servers:
#        spam_bayes: ["127.0.0.1:9001"]



###############validator config##################
#如果需要添加验证器，只要配置好类全名即可
#替换验证器实现，则替换相应的类名即可
#warning: 自定义验证器实现需要线程安全

validator:
   format:        net.csdn.validate.impl.Format
   numericality:  net.csdn.validate.impl.Numericality
   presence:      net.csdn.validate.impl.Presence
   uniqueness:    net.csdn.validate.impl.Uniqueness
   length:        net.csdn.validate.impl.Length
   associated:    net.csdn.validate.impl.Associated

mongo_validator:
   format:        net.csdn.mongo.validate.impl.Format
   numericality:  net.csdn.mongo.validate.impl.Numericality
   presence:      net.csdn.mongo.validate.impl.Presence
   uniqueness:    net.csdn.mongo.validate.impl.Uniqueness
   length:        net.csdn.mongo.validate.impl.Length
   associated:    net.csdn.mongo.validate.impl.Associated

################ 数据库类型映射 ####################
type_mapping:  net.csdn.jpa.type.impl.MysqlType

qps:
   /song/songDetail: 10

qpslimit:
   enable: true
dubbo:
   disable: false
   server: true
